[server]
host = "0.0.0.0"
port = 9000

[workers]
    [workers.messenger_cron]
    command = "/usr/bin/php /home/max/Projects/opsway/devarea/ipc/worker.php"
    number = 3

[timers]
    [timers.cron_process]
    command = "bin/app cron:process"
    frequency = 60  # seconds
