[server]
host = "0.0.0.0"
port = 9000

[workers]
    [workers.messenger_consume]
    command = "bin/app messenger:consume messenger.transport.amqp"
    number = 2

    [workers.messenger_cron]
    command = "bin/app messenger:consume messenger.transport.some_else"
    number = 1

[timers]
    [timers.cron_process]
    command = "bin/app cron:process"
    frequency = 60  # seconds
